### ISSUE TITLE
Math incorrect?

### ISSUE THREAD

**Issue by wcomfort** [learn-co-curriculum/fewpjs_default_rest_spread_as_function_arguments-to-get-started#10]
function discountedAndTaxedPrice(itemPrice, discount = 0.25, tax){
    return itemPrice - (itemPrice * discount) + (itemPrice * tax)
}
discountedAndTaxedPrice(100, 0.15, 0.08) //=> 185.0799.... 

this bit right here is very confusing. I don't understand how this math is working and I cant figure our what adding undefined as a parameter does.

**Comment by sgharms** [comment]
We just updated this example yesterday, @wcomfort. Take a look at the version here:

https://github.com/learn-co-curriculum/fewpjs_default_rest_spread_as_function_arguments-to-get-started/

And let us know if it makes more sense. For further questions about this, use AAQ!
