### ISSUE TITLE
Unclear instructions

### ISSUE THREAD

**Issue by jenniferbusca** [learn-co-curriculum/fewpjs_default_rest_spread_as_function_arguments-to-get-started#5]
<img width="892" alt="Screen Shot 2019-08-28 at 9 47 41 AM" src="https://user-images.githubusercontent.com/25334564/63861477-fda1ab00-c978-11e9-8265-26d8227c8ab8.png">
I'm unclear on how this demonstrates how to use undefined for an unspecified variable.

**Comment by sgharms** [comment]
We've updated our guidance per your feedback. Thanks!
