### ISSUE TITLE
Wrong example given

### ISSUE THREAD

**Issue by george-kirby** [learn-co-curriculum/fewpjs_default_rest_spread_as_function_arguments-to-get-started#7]
> It's common to get the "default" value by simply not providing an argument. In this call, we simply leave off the optional discount percentage.

-> should be followed by:
`discountedPrice(100) //=> 75`
..rather than..
`discountedPrice(100, 0.5) //=> 50`

**Comment by sgharms** [comment]
Thanks, updated!
