### ISSUE TITLE
Incorrect example

### ISSUE THREAD

**Issue by thistonyb** [learn-co-curriculum/fewpjs_default_rest_spread_as_function_arguments-to-get-started#9]
The explanation about default includes this example:
// BREAKS:
// discountedAndTaxedPrice(100). JavaScript sees (100, 0.15, Not-a-number)
// to make this work tax would also need a default value.

This is incorrect. It would not see 0.15 as it was not passed into the function call, so it uses the default.

Also, explaining that putting the default at the end of the parameters when creating a function would avoid the not-a-number error. And might be helpful and a better way to create the function. Since default is common and normal to put at the end of a bunch of parameters, someone might make a mistake of assuming anything after a default was also default - causing a bug.
 
Thanks!

**Comment by sgharms** [comment]
Seems good. Will adjust.
